### ISSUE TITLE
Erroneous "Cannot read properties of undefined" linting errors caused by `@keyframes` in `<style>`

### ISSUE THREAD

**Issue by zachstence** [sveltejs/eslint-plugin-svelte#857]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.10.0

### What version of `eslint-plugin-svelte` are you using?

2.44.0

### What did you do?

`@keyframes` without a name:
```css
@keyframes {
}
```

`@keyframes` with an `@apply`
```css
@keyframes myKeyframes {
	100% {
		@apply text-red;
	}
}
```

### What did you expect to happen?

No linting errors should happen when using `@keyframes` without a name or with an `@apply`

### What actually happened?

![image](https://github.com/user-attachments/assets/8b8139c4-a36d-48a8-bad6-718b0427432b)

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/zachstence/keyframes-apply-eslint-repro

**Comment by mikededo** [comment]
Hello @zachstence!

Your issue is due to using the `@apply` function in a `<style>` tag without the `lang="postcss"` attribute. Note that in order to use any Tailwind functions, which use `postcss`, you must add the `lang="postcss"` param to the `style` tags. However, *Tailwind functions cannot be used inside* `@keyframes` (yet).  

Check [this comment](https://github.com/tailwindlabs/tailwindcss/issues/11072#issuecomment-1521989962) where it says:

> As an aside, we'd recommend not using @apply with @keyframes. It wasn't designed to work with it and you can get it to produce some pretty comical, non-sensical results

**Comment by mikededo** [comment]
Also, `@keyframes` directive must include a name. See the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes)
